spring.application.name=backend
server.port=8080

spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.uffydyvsfwuetgivltfr
spring.datasource.password=Akash!314325
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=7dca8c5af7191244f77688ad7cda5eb9255a24d5b201facc951010bb150d182283ccb8830156d9be8c903dc2f9aa7eabc93b59363bc64aef2e8dc771221ac192
jwt.expiration=86400000

logging.level.org.springframework.security=DEBUG
